### ISSUE TITLE
Screenshot option not being saved

### ISSUE THREAD

**Issue by Mrbysco** [blay09/EiraIRC#102]
I keep setting my screenshot setting to 3 (Upload & Clipboard) but on restart its automaticly set to 2.. which I do not want. I can reproduce this as much as I want...

"    # 0: None / 1: Upload / 2: Upload & Share / 3: Upload & Clipboard
    I:screenshotAction=2" <-- is what happens every bootup... 
I hate it cuz I almost got banned / muted of a livestream...

**Comment by jusvit** [comment]
It won't let me change the Auto-Perform-Action, i change it get out of menu and it defaults back to none
