### ISSUE TITLE
unable to use the MC help command

### ISSUE THREAD

**Issue by AEnterprise** [blay09/EiraIRC#119]
i have it installed on both the client and the server, server is joining a chanel and using the server profile, client has nothing setup no servers or anything and is thus chattting to minecraft.

but when i run the "/help" command i get an error message on the client saying there was an unknown error trying to perform this command

the server console spits out this error: http://www.hastebin.com/xilesopeci.hs

**Comment by blay09** [comment]
Whoops. Indeed. Fix incoming.

**Comment by blay09** [comment]
Builds with this fix included are available on my jenkins at http://blay09.net:8080/jenkins/
