### ISSUE TITLE
Mod only checks for # type channels

### ISSUE THREAD

**Issue by rcmaehl** [blay09/EiraIRC#123]
The mod, specifically IRCConnectionImpl.java and possibly other components, only checks for channels starting with '#' when channels can start with '&', '#', '+' or '!'.

For future proofing you should check for any type specified in CHANTYPES="" on 005 RPL_ISUPPORT

## Sample
`:labyrinth.ga.us.irchighway.net 005 DiceBot SAFELIST SILENCE KNOCK FNC WATCH=128 CHANLIMIT=#&:30 MAXLIST=be:60 NICKLEN=30 TOPICLEN=307 KICKLEN=307 CHANNELLEN=32 :are available on this server`
`:labyrinth.ga.us.irchighway.net 005 DiceBot EXCEPTS=e CHANTYPES=#& PREFIX=(aohv)!@%+ CHANMODES=be,k,l,cimnpqstAKMNORS STATUSMSG=!@%+ NETWORK=IRCHighWay CASEMAPPING=ascii STD=i-d :are available on this server`

Implies '#' and '&' should be checked.

## References:
https://tools.ietf.org/html/rfc2812#section-1.3
http://en.wikipedia.org/wiki/Internet_Relay_Chat#Channels

**Comment by blay09** [comment]
Thanks for the great issue report, makes making EiraIRC open-source worth it (considering I myself barely know(/knew) any of the more indepth IRC stuff). :)
