### ISSUE TITLE
Slash Command Clashes

### ISSUE THREAD

**Issue by darkrising** [blay09/EiraIRC#124]
Hello, I just found this IRC mod a few hours ago and I want to use it on my server. However I'm using a mod that allows the user to change their display name and give their self a group with colours etc etc.

The problem I ran into is that this mod uses the commands /nick and /color already so the other mod can't. 

Would it be possible for you to add a config to rebind slash commands?

I could download and make the changes myself but I thought I'd ask first :)

I'm using version for 1.7.10.

**Comment by blay09** [comment]
registerShortCommands = false in the config file to solve. The actual EiraIRC commands are all within the /irc and /sirc (for servers) commands, all others are just short forms (e.g. /nick for /irc nick)
