### ISSUE TITLE
sends garbled auth command to qbot (quakenet)

### ISSUE THREAD

**Issue by draeath** [blay09/EiraIRC#132]
From the server logs in debug mode:
```
[22:12:54] [Thread-39/INFO] [STDOUT]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:run:199]: :Q!TheQBot@CServe.quakenet.org NOTICE [nickname] :Unknown command [password]. Type SHOWCOMMANDS for a list of available commands.
```
Substitude [nickname] for the value set with S:nickServName, and [password] for the value set by S:nickServPassword

Unfortunately due to another issue (haven't searched if there's an open one or if I need to create it) the actual outbound text is not visible:
```
[22:12:54] [Thread-39/INFO] [STDOUT]: [net.blay09.mods.eirairc.irc.IRCConnectionImpl:handleNumericMessage:342]: Unhandled message code: 366 (3 arguments)
```

I have tried adjusting services.cfg to no avail. I don't believe '/servirc config reload' reloads this file, as the following seems to change nothing (given the behavior above I would expect it to shift the arguments over at least)
```
S:cmdIdentify=PRIVMSG Q@CServe.quakenet.org AUTH {USER} {PASS}
```

**Comment by draeath** [comment]
I'm trying to get a useful packet capture for this, so we can see what is being sent.

**Comment by draeath** [comment]
Found the problem: Raw text in TCP capture shows a missing ":" before the identify command text:

```
text sent to IRC server:
PRIVMSG Q@CServe.quakenet.org AUTH ######## ##########

text returned from IRC server:
Q!TheQBot@CServe.quakenet.org NOTICE ######## :Unknown command ##########. Type SHOWCOMMANDS for a list of available commands.
```

**Comment by blay09** [comment]
The default identify command should be "S:cmdIdentify=AUTH {USER} {PASS}" though, unless you're running a very old EiraIRC version. Quakenet has a native server command AUTH that pretty much does the same as "PRIVMSG Q@CServe.quakenet.org :AUTH ######## ##########".

**Comment by draeath** [comment]
It wasn't working as-is, haven't been able to figure out why. Does the servername matching work based on configuraiton, or based on where you actually connect? For example, when I last connected irc.quakenet.org actually put me on port80b.se.quakenet.org.

Using eirairc-mc1.7.10-v1.7.56.jar from Jenkins, btw.

Also, it looks like the bots configuration files don't get read on a config reload either - I set B:allowPrivateMessages true and reloaded, and was politely informed that they were not enabled when I retried. I'll leave a note in #134

**Comment by blay09** [comment]
The matching takes the address specified in the configuration. 

I'll test it myself and find out why it's not working with the default command.

**Comment by draeath** [comment]
Apologies in advance if it's working fine now. Combination of #134, Q bot maintenance, and suddenly a full population on the server I'm installing this into means I've probably been using the invalid cmdIdentify this whole time.

**Comment by draeath** [comment]
Yep, working fine now that I put your default back in and actually had it in effect while Q was operable. Sorry for the bother!

**Comment by blay09** [comment]
No problem, thanks for testing it again in my place :)
