### ISSUE TITLE
Gradle script

### ISSUE THREAD

**Issue by dmodoomsirius** [blay09/EiraIRC#159]
just either change the output or run clean and it does the same thing. no clean will not mess with you being able to compile. clean cleans the build dir.
https://github.com/blay09/EiraIRC/blob/master/build.gradle#L59-L61

**Comment by blay09** [comment]
Hacked that up a while ago to set up my jenkins and didn't think of simply running clean to get rid of the old file. Will try it in a bit, thanks :)

**Comment by dmodoomsirius** [comment]
no prob. thought id let you know

**Comment by dmodoomsirius** [comment]
You could keep the delete and do https://github.com/BuiltBrokenModding/BuiltBrokenScripts/blob/master/scripts/jars.gradle#L5 and change the delete to delete that folder as well
