### ISSUE TITLE
servirc msg doesn't handle complex nicknames

### ISSUE THREAD

**Issue by draeath** [blay09/EiraIRC#166]
Example:
/servirc msg "Q@CServe.quakenet.org" AUTH username password
[Server thread/INFO]: The server at "Q@CServe.quakenet.org" cannot be found.

The quotes do not seem to make a difference, you get the same error with or without.

In this case, this prevents manual auth against Q (eg if Q was down when the bot initialized), as you must use this full name to use the AUTH command:
[Thread-55/INFO]: [(Q)] To prevent sensitive information being accidentally send to malicious users
[Thread-55/INFO]: [(Q)] on other networks, when using the AUTH command, you must use
[Thread-55/INFO]: [(Q)] /msg Q@CServe.quakenet.org.

**Comment by draeath** [comment]
Workaround is to disconnect and reconnect the bot, but msg should still be able to take a wierd username and pass it through to IRC unmolested.

**Comment by blay09** [comment]
Another workaround is to put the server address in front like: irc.quakenet.org/Q@CServe.quakenet.org - usually that shouldn't be needed when connected to only one server, but for some reason here it is. Will fix.
