### ISSUE TITLE
IRC nick change causes bot to throw an exception.

### ISSUE THREAD

**Issue by cullorblind** [blay09/EiraIRC#176]
/nick changes in the irc channel are causing an exception to be thrown which causes the bot to quit working and lose connectivity.  /ircserv disconnect/connect &lt;ip&gt;  will get it back into the channel and back online.

The exception is logged immediately when the nick change occurs, and the irc connection times out after a minute or two:  http://hastebin.ke5kul.prwn.net:7777/epeta.txt

In this example, nG is one of three PurpleIRC bots we have on Spigot, and MM is the EiraIRC bot on forge.
Immaridel is now known as HAL
04:52PM &lt;nG&gt; &lt;RavaKeeva&gt; Oh no...!
04:52PM &lt;HAL&gt; I'm in control now, Dave.
SignOff MM: #GIBCraft (Ping timeout: 20 seconds)

And Thanks for creating a decent forge irc bot.  I've played with a few of the others, and they're all fairly lacking so far.

edit: lt/gt symbols weren't being displayed.

**Comment by blay09** [comment]
Log file is down.

**Comment by cullorblind** [comment]
Woops.  Might help if I posted the public domain name.   http://hastebin.prwn.net:7777/epeta.txt
