### ISSUE TITLE
shared.cfg is overwritten on `/servirc config reload`

### ISSUE THREAD

**Issue by RoyCurtis** [blay09/EiraIRC#180]
When executing `/servirc config reload`, EiraIRC appears to overwrite `shared.cfg` with its in-memory setting, then reloads the config from file, thus applying no changes.

## Details

* [DW20 1.7.10 1.2.1 server](https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.2.1)
* EiraIRC: `eirairc-mc1.7.10-2.8.151.jar`

## Reproduction

1. Whilst server is running and EiraIRC is connected to a channel, open `shared.cfg`
2. Change a setting, e.g. `B:relayNickChanges=true` to `B:relayNickChanges=false`
3. Save `shared.cfg`
4. In-game, do `/servirc config reload` and wait for reconnection
5. On IRC, change nickname (e.g. `/nick someothernick`)
6. Observe that EiraIRC relays the nick change, despite having set it to false
7. Re-open `shared.cfg`, observe that `B:relayNickChanges=false` has been changed back to `B:relayNickChanges=true`

**Comment by RoyCurtis** [comment]
Thank you very much for solving this and accepting the pull request!

**Comment by blay09** [comment]
:heart:
