### ISSUE TITLE
Servirc Alias not working properly

### ISSUE THREAD

**Issue by Fogger** [blay09/EiraIRC#183]
Version: 2.8.128

**From Client:**
Typing `/servirc alias <new-custom-nick>`  returns `That player cannot be found.`

Typing `/servirc alias <official-mc-name> <new-custom-nick>` returns:

    Alias for <old-custom-nick> set to <new-custom-nick>
    <old-custom-nick> is now known as <official-mc-name>

so whatever I do, my name is always the official-mc-name

**Comment by blay09** [comment]
Tested just now on 2.8.154 and it worked. Not sure if I maybe fixed it somehow already.
If it still won't work for you on that version, it could be that some other mod is messing with your name at a higher priority order (unlikely though since EiraIRC runs as highest for name changes).
