### ISSUE TITLE
commands output can cause excess flood

### ISSUE THREAD

**Issue by draeath** [blay09/EiraIRC#219]
Commands output can cause the bot to be kicked from the IRC server for excess flood. Adding an option to throttle output (perhaps beyond an arbitrary line count in commands.json) is an option.

For example, tickprofiler's tps measurement spans many lines, and when the bot attempts to relay this output (either to the channel as a whole, or back via a PM) quakenet slaps it down.

Expanding further, allowing a regex or 'grep-like' filtering of a command would be excellent - in the cases where you only care about specific parts of a command output.

**Comment by blay09** [comment]
EiraIRC will limit itself a little now if it's trying to send too much data at once. I was able to send 24 messages at once before getting kicked now. Config option "antiFloodTime" can be adjusted to specific needs.
