### ISSUE TITLE
Disable sending IRC channel member list to MC players on join

### ISSUE THREAD

**Issue by redsgreens** [blay09/EiraIRC#238]
The "AutoWho" parameter would seem to be the one I want, but toggling it on/off does not stop the mod from announcing who is in the IRC channel to MC players when they join. I looked in the code a bit and perhaps I'm misunderstanding but in MCEventHandler.java there is this code in the onPlayerLogin event handler: 

if (generalSettings.getBoolean(GeneralBooleanComponent.AutoJoin)) {
	Utils.sendUserList(event.player, connection, channel);
}

This looks wrong to me. I want the bot to AutoJoin my server and channel so I can't disable that. However, if I let the bot join my channel and then disable AutoJoin then it stops announcing the IRC members to MC players. Should this be changed from a test for AutoJoin to AutoWho?

**Comment by blay09** [comment]
Woops! Good catch. Fix incoming.
