### ISSUE TITLE
Getting started site not working

### ISSUE THREAD

**Issue by Gunner76th** [blay09/EiraIRC#240]
I tried to access your documentation site to find out what color was assigned to what number, only to find out that the site seems to be down. When I attempted to go to the main page (IE remove the /?page_id=63) I was met with what looks to be a hacked version of the original site. The original presentation of the site is here: https://www.dropbox.com/s/rk4dn94aaygy0wh/Screenshot%202015-04-25%2009.18.52.png?dl=0

This is what the site looks like after sent through Google Translate: https://www.dropbox.com/s/l3rparyacf713uw/Screenshot%202015-04-25%2009.25.09.png?dl=0

**Comment by blay09** [comment]
Server was offline for a bit but is back up now.
