### ISSUE TITLE
Duplicate Chat Messages

### ISSUE THREAD

**Issue by Redlotus99** [blay09/EiraIRC#257]
In Minecraft when a player types a message it is repeated by the bot and relayed to IRC. It only shows once in IRC but twice in MC chat. I cannot the users chat to show in IRC without the bot in the channel, but in MC chat they can see me typing if I am in the IRC channel.

It is quite odd and I cannot figure this out. Any help would be greatly appreciated.

**Comment by blay09** [comment]
Are there maybe two EiraIRC bots connected OR do you have it installed and connected on the client too?

**Comment by Redlotus99** [comment]
I will update using the one released today first then go from there.

There is only one bot connecting as shown in IRC. I do have the mod installed on the server and in my modpack for the client.  I see my users in IRC just nothing was being relayed so I had the bot connect to IRC and it did so successfully and upon doing so I could see users typing from MC to IRC and vice versa. The only issue I saw was in MC where the user would type something and then the bot would repeat it.

I will update the mod and see if the issue persists.

**Comment by blay09** [comment]
If you are in the same channel with your client-side EiraIRC as the server-side EiraIRC bot is sitting, you're going to see both the messages on IRC (from your client) and the messages in Minecraft (from the server).

**Comment by Redlotus99** [comment]
Anything that would prevent a user typing something in MC to not be relayed to IRC?

**Comment by blay09** [comment]
* "readOnly" option being true
* channel being +m but the bot not having voice
* channel requiring auth to speak but bot not being authenticated
* other mods exclusively handling chat events (if !who doesn't work when typed in Minecraft chat, it's a compatibility issue)

Other than that, there shouldn't be anything causing problems.
Drop your config files on pastebin or something if you want me to take a look (but make sure to strip nickserv data from it and such)

**Comment by Redlotus99** [comment]
It seems when the clients connect to the IRC channel and the bot is there also it duplicates the messages.  If I kick all the players from IRC and leave the bot in place the messages are not duplicated.  If I disconnect the bot from IRC and let the clients/players stay in the channel they can see me typing from IRC but I cannot see them typing from MC to IRC even though it shows them in the channel.

**Comment by blay09** [comment]
Yes, as I've said above, you only really install EiraIRC either on the clients or on the server. The server version will relay all Minecraft chat to IRC and vice-versa. The client version acts as a normal IRC client where every user has their own connection and active chat can be switched with TAB.

**Comment by Redlotus99** [comment]
Understood I apologize for my confusion. You can close this. This was caused by having the clients/players connected to the IRC channel via the client and the Bot in the same channel which in turn generated duplicate messages.

**Comment by blay09** [comment]
Alright, glad you got it sorted out! :)
