### ISSUE TITLE
Crash with EiraIRC after adding LLibrary to existing pack

### ISSUE THREAD

**Issue by Haggle1996** [blay09/EiraIRC#281]
https://gist.github.com/Haggle1996/0d33a960241f13aad705

Receiving the above error after adding LLibrary to an existing pack (http://bit.ly/1CLRfNc). It looks like a conflict with EiraIRC. I've tried several different versions of EiraIRC, but none work. Cross-posting to both issue trackers. 

ILexiconn/LLibrary#26

**Comment by iLexiconn** [comment]
This can be fixed by checking if LLibrary is installed, and if that's the case, check if net.ilexiconn.llibrary.client.ClientEventHandler.screenshotKeyBinding is clicked instead of Minecraft.getMinecraft().gameSettings.keyBindScreenshot

**Comment by blay09** [comment]
I'd rather not do that. What's the point of your own screenshot implementation? I couldn't see any difference after having a quick look.

Anyway, I added a check for getKeyCode() being > 0, so it shouldn't crash anymore - EiraIRC's automatic screenshot actions however will not work.

Builds with the fix will be ready at http://jenkins.blay09.net/ in a sec.

**Comment by Haggle1996** [comment]
Thanks, blay09. As usual, you are awesome!
