### ISSUE TITLE
Server achievement sending to IRC fires even when the player is ineligible for the achievement

### ISSUE THREAD

**Issue by Monstrel** [blay09/EiraIRC#296]
In order to earn achievements, they must be unlocked by earning prior achievements.  EiraIRC is ignoring this and firing whenever the basic condition for the achievement is met (mining diamonds, for instance) regardless of the player's ability to earn that achievement.  Using mods such as Tinker's Construct, one can bypass many of the basic achievements and leave most of the achievement tree closed off.  This can cause achievement announcements to reach IRC several times in a row when they never fire in game for the player who triggers them, such as when mining a vein of multiple diamond ore blocks.

**Comment by blay09** [comment]
God damn it @tterrag1098, you deserve that ban! :p

Thanks, will be fixed in the next version.

**Comment by tterrag1098** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/1265

**Comment by blay09** [comment]
Yeah, the event would have either needed better documentation or have the checks done before it's fired.

But I can't complain, I wouldn't even know how to properly submit a PR to Forge.. (and I'm too lazy to find out really) /o\

**Comment by tterrag1098** [comment]
Honestly I'd prefer the more general case be when it's fired. Maybe you want to respond to achievements that have already been gotten by the player. Who are we to determine what mods should be doing? The checks are not hard to do.
