### ISSUE TITLE
AutoJoin of +R channels doesn't work because it doesn't wait for a response from NickServ

### ISSUE THREAD

**Issue by blay09** [blay09/EiraIRC#300]

**Comment by blay09** [comment]
This is going to be a little harder to fix because there's no standard response on a succeeded IDENTIFY. NickServ on esper just sends a notice, for example.

**Comment by Zarthus** [comment]
If you're going to do a string comparison different services return different strings.

A configuration option for the nickserv identify return string and nickserv name would be required.

Rough example: https://github.com/znc/znc/blob/master/modules/nickserv.cpp#L96-L106

An alternative might be to implement SASL support, or retrying to join the channel after an arbitrary amount of seconds, like 30.

**Comment by Unknown-Zombie** [comment]
I'm still having issues auto-joining +R channels in version 1.7.10-2.9.391.

EiraIRC will join channels before NickServ login happens, and thus I am always dumped into #RegisterYourNameMoron instead of #MinecraftForge
