### ISSUE TITLE
#295 is not fixed. !who is still hardcoded in IRCCommandHandler.java

### ISSUE THREAD

**Issue by lf-** [blay09/EiraIRC#304]
#295 is not completely fixed by 1df676b. !who is still hardcoded in IRCCommandHandler.java.

**Comment by blay09** [comment]
That's the !who command that can be used from within Minecraft chat to list the IRC users; all commands that are run from within an IRC channel use the customizable ircCommandPrefix.

I guess I could use the option for this one too though...

**Comment by lf-** [comment]
Well it does seem inconsistent that getting the players via irc is different from ingame.
