### ISSUE TITLE
Better API

### ISSUE THREAD

**Issue by SoniEx2** [blay09/EiraIRC#306]
Can we get a better API? Thanks.

**Comment by blay09** [comment]
You're gonna have to clarify what exactly you want.

**Comment by SoniEx2** [comment]
Well a way to control the chat output with Lua scripts would be cool.

That way we can parse IRC messages and turn bot messages into chat messages, so it's less... bloated, and feels like you're playing on a server, kinda.

For example, the Queercraft IRC bot, on `#queercraft @ EsperNet`. [I have a HexChat plugin that makes the bot messages look like normal IRC messages](https://github.com/SoniEx2/Stuff/blob/master/hexchat/python/qc.py). It would be cool to be able to write similar plugins for use with EiraIRC.

Altho maybe an Event API (API based on Forge events) would be better, as it would allow the plugins to be written in any language.

**Comment by SoniEx2** [comment]
Here's my idea for an event-based API:

IRCEvent.java
```java
// add imports here

// annotations for cancellable and has result
public class IRCEvent extends Event {
    public final IRCNetwork network;
    public ChatComponent chatMessage; // the thing that shows up in in-game chat, if the result is set to ALLOW
    // add constructor here
}
```

IRCChannelEvent.java
```java
// add imports here

public class IRCChannelEvent extends IRCEvent {
    public final IRCChannel channel;
    // add constructor here
}
```

IRCChannelMessageEvent.java
```java
// add imports here

public class IRCChannelMessageEvent extends IRCChannelEvent {
    public final User user; // this includes hostname, nickname, ident, nickserv username, etc and can be expanded as needed
    public final String message; // the contents of the message
    // maybe it'd be better to make this "IRCMessageEvent" and have an optional "channel" field, actually.
    // add constructor here
}
```

It's obviously a rough draft but w/e.

**Comment by blay09** [comment]
EiraIRC already has an event-based API:

https://github.com/blay09/EiraIRC/tree/master/src/api/java/net/blay09/mods/eirairc/api

**Comment by SoniEx2** [comment]
O I see.

Apparently it doesn't let me implement CTCPs tho, so it's shit.

**Comment by blay09** [comment]
Go ahead and pull request then. Opening an issue with little to no information ("can haz lua scripting pls") and then calling my API shit certainly won't get me to do it for you.
