### ISSUE TITLE
bridged commands

### ISSUE THREAD

**Issue by skittishtrigger** [blay09/EiraIRC#314]
sending commands via chat in game do not seem to trigger inside the irc channel.  I suggest those opped (or have a configurable permission node using standard eirairc.command.whatever) sending a (raw?) message for channel control using bots. As an example, ---   .lart name ---   will tell me bot to randomly do some action against the person named. would be useful also for mods in game also.

**Comment by blay09** [comment]
A workaround for this should be the /servirc msg command that allows OPs to send messages without the <Nick> part in front.

I might add some kind of option for message prefixes that get sent without the nick prefix for OPs.

**Comment by skittishtrigger** [comment]
Thanks for the fast response. and so far I am loving your mod. Good job on it.  
ya, making it op only (or specifying an override with the perms ability by custom command) would definitely be a good way to go just to prevent spamming non-essential irc commands like /who or the various "fun" bot commands.

I don't know how it is in your code but however your commands are injected into the game the ideal setup would be something like this:

(my permissions adding)
/mangaddp eirairc.commands.sirc.bot."custom"(variable) builder(group) might need quotes cause of how some bots are prefixed for compatability.


custom:
".lart"
".8ball"
"adduser"
"etc"
"etc"

just some input. Once again, I appreciate it. thank you!
