### ISSUE TITLE
Can't seem to upload screenshots when any GUI elements are present

### ISSUE THREAD

**Issue by plazia** [blay09/EiraIRC#316]
eirairc-mc1.7.10-2.8.293

I bound the upload+share screenshot key to F2. 

If I press it any time I can successfully take a screenshot and upload it to imgur and it posts a link in the channel that's fine.

However if I have any GUI elements up like I'm looking at a machine's GUI or I have the inventory up or anything with any GUI... it will not upload the screenshot at all.

**Comment by blay09** [comment]
This is a consequence of moving my keybinds over to Vanilla's keybinding system; the events are not fired when GUI screens are visible (this will be solved in Minecraft 1.8+).

I might add a workaround that adds a special case for the screenshot key.
