### ISSUE TITLE
EiraIRC Causes Odd Graphical Glitches

### ISSUE THREAD

**Issue by pacificfils** [blay09/EiraIRC#329]
Tested on Minecraft 1.8.0 on Windows 10/Java 1.8.0_25. Graphics Card is NVIDIA GT745M. Optifine is installed, version 1.8.0 HD U D5.

I isolated this issue down to EiraIRC -- this issue does not exist if the mod is disabled.

![](http://i.imgur.com/VhxUiCg.png)

I am able to provide any more configs as needed.

On build 258.

**Comment by blay09** [comment]
Can you try disabling the fancy overlay (/irc config global eirairc_enableFancyOverlay false) and see if that fixes it?

**Comment by pacificfils** [comment]
> Can you try disabling the fancy overlay (/irc config global eirairc_enableFancyOverlay false) and see if that fixes it?

Appears to have done the trick after a full game restart. Will keep you posted if it comes back.
