### ISSUE TITLE
Bot is very trigger-happy

### ISSUE THREAD

**Issue by KazWolfe** [blay09/EiraIRC#340]
In PMs, the bot will always respond, no matter what was said or who said it.

Disabling in the config menu seems to have no effect:

![](http://i.imgur.com/wC55bbO.png)

(bottom message is bot)

**Comment by blay09** [comment]
This should only happen on server-side bots, I'll have a look.

**Comment by blay09** [comment]
I tested this and it does indeed only happen with server side bots. That's supposed to be like that, it is a bot after all. What's the issue?

**Comment by KazWolfe** [comment]
I have EiraIRC installed on my client (not the server), and sending or receiving messages in the IRC window triggers the bot to respond with the "UNKNOWN COMMAND" response.

**Comment by blay09** [comment]
Are you on the latest version? I checked the code too and unknown command is definitely only sent from servers.

**Comment by KazWolfe** [comment]
I'll try the latest version soon.

**Comment by BlayTheNinth** [comment]
Any news on this or can I close it?
