### ISSUE TITLE
/me dumps an enormous JSON string to the chat

### ISSUE THREAD

**Issue by Baughn** [blay09/EiraIRC#341]
It looks somewhat like this:

TextComponent{text='Baughn', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg Baughn '}, hoverEvent=null}} TextComponent{text='', siblings=[TextComponent{text='goes to report simply's problem.', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

The same message is correctly relayed to IRC.

**Comment by Baughn** [comment]
Is this supposed to be fixed in 2.9.391? I still have the same problem.

**Comment by blay09** [comment]
It should be fixed, yeah. Are you running on a client or a server?

**Comment by Baughn** [comment]
EiraIRC is running on the server. It's not on my client... let me try that.

**Comment by Baughn** [comment]
Nope, same problem either way.

**Comment by GinjaNinja32** [comment]
Also happening for me on 2.9.391.
![](http://151.80.68.132/i/2015-10-24_14:52:25.png)

**Comment by Baughn** [comment]
I can confirm, that commit fixes it.

**Comment by GinjaNinja32** [comment]
Yep, fixed here as of build 392.
