### ISSUE TITLE
Issue with auto reconnect

### ISSUE THREAD

**Issue by MarkYSA** [blay09/EiraIRC#342]
Hi.

Could you please set auto-reconnect function to execute every 15 seconds, not one time?

P.S. For 1.7.10

Thanks!

Regards, Mark

**Comment by blay09** [comment]
Auto-reconnect should already happen whenever needed, with increasing delays on consecutive failed attempts.

**Comment by MarkYSA** [comment]
Hi,

Please check log output from mc server console:

01.10 18:52:24 [Server] INFO test
01.10 18:50:49 [Server] INFO Could not connect to irc.somedomain.com: java.net.ConnectException: Connection refused
01.10 18:50:34 [Server] INFO Reconnecting to irc.somedomain.com in 15 seconds...

As we can see, reconnect is happens only one time.

**Comment by blay09** [comment]
What happens after those 15 seconds? Anything else in the log?

**Comment by MarkYSA** [comment]
Unfortunately nothing.

**Comment by BlayTheNinth** [comment]
Can't reproduce the issue with the information I've got. Does the same happen on Vanilla Forge servers? There should at least be some kind of error after the 15 seconds if it doesn't just silently reconnect.
