### ISSUE TITLE
[Upload & Share] Link in Screenshot Message

### ISSUE THREAD

**Issue by LJack2k** [blay09/EiraIRC#343]
I know it say's deprecated on the tool tip. And I'm fine with it that it's not set upload and share by default. But I doesnt allow me to enable it when I want. Not even the option upload is allowed. Is this intended? Is there something else coming that makes it easy to share a screenshot again? I know the route how to do it now. Screenshot->Upload->Copy to clipboard->paste in chat. Could this feature be enabled again and default way on none so people can choose.
Or is it possible to make it so that after a screenshot is made the chat asks you what you want to do. Like: You made screenshot.png bla bla bla. Do you want to upload and share? Yes / No?
Don't know if that is possible. Thanks in advance.
Greetings,
LJack2k

**Comment by blay09** [comment]
I don't think it's intended, but I'd like to encourage people to use the screenshot & share keybind (configurable in the Minecraft controls) instead. Uploading every screenshot ever being taken just doesn't feel right to me.

I might add a clickable [Upload & Share] link to the chat message.
