### ISSUE TITLE
Minecraft won't start

### ISSUE THREAD

**Issue by Chewsterchew** [blay09/EiraIRC#344]
I am using the latest version of both forge and EiraIRC.
[Crash Report](http://paste.ubuntu.com/12765932/)

It goes to stage 5 then it crashes.
I have no other mods installed.

**Comment by Chewsterchew** [comment]
It works with a modpack I use (it was a 1.7.10 modpack)

**Comment by blay09** [comment]
Update to the latest Forge version.

**Comment by Chewsterchew** [comment]
Ah, I guess I wasn't updated far enough, thanks!
