### ISSUE TITLE
Line breaks in Minecraft chat reset color to white

### ISSUE THREAD

**Issue by GinjaNinja32** [blay09/EiraIRC#346]
![](http://nyx.gn32.uk/old/i/2015-10-26_18:24:02.png)
![](http://nyx.gn32.uk/old/i/2015-10-26_18:24:08.png)

**Comment by BlayTheNinth** [comment]
Fixed in https://github.com/MinecraftForge/MinecraftForge/commit/74fe6902277c70ca31128c37e45b1e79dd21244d, Minecraft 1.8.9+
