### ISSUE TITLE
Integration with Dynmap-Forge works only one way

### ISSUE THREAD

**Issue by redsgreens** [blay09/EiraIRC#347]
Using latest EiraIRC development version 1.8-3.9.270 (also tested with 269) and Dynmap-Forge 2.2, chats from IRC do not get relayed to the Dynmap webchat, but messages sent from the Dynmap webchat do get sent to IRC.

**Comment by redsgreens** [comment]
Anything I can do to help confirm this issue?

**Comment by BlayTheNinth** [comment]
No, it's just a silly oversight. Will be fixed next version.

**Comment by redsgreens** [comment]
Can confirm, fixed in build 272. Thank you!
