### ISSUE TITLE
relayBroadcasts Spam

### ISSUE THREAD

**Issue by Lartza** [blay09/EiraIRC#348]
Having relayBroadcasts on by default, or having ircBroadcastMessage in it's current format allows anyone to spam IRC channels if they constantly use /say.

**Comment by blay09** [comment]
But /say is an OP-command, why would OPs use it to spam?

**Comment by Lartza** [comment]
Because people are what they are. It's an issue with the fact that you can join IRC channels with EiraIRC that you don't own.

It's actually useful when you set EiraIRC to join your community's IRC channel for example, but that isn't always how EiraIRC is used.

**Comment by blay09** [comment]
Okay, you got the core of the problem wrong but I get what you mean now. The real problem is that I forgot to check for permission on EiraIRC's relayBroadcasts hook. It's only supposed to work for server OPs (and if those were to use it to spam then you picked the wrong server OPs). Will fix.

**Comment by Lartza** [comment]
That's not what I mean though. Since you can have EiraIRC on your server, be an op, join to any IRC channel and spam with /say.

Of course you'd probably get kicked out of IRC but it still allows this for the duration an op is not available to ban the user, and somebody might use it without knowing better.

**Comment by BlayTheNinth** [comment]
Or you could just grab any IRC client, join to any IRC channel and spam normally.
Or you could, since you're an OP, run /irc config global relayBroadcasts true and start spamming then.

Don't op idiots who abuse /say to spam and you won't have problems. If you do, that's your own fault.

**Comment by Lartza** [comment]
In my opinion this is kind of like having a default alias /ANNOY in the said IRC client. Sure, people don't have to use it but it is there.

This issue for example emerged from people using /say in #rr, where you aren't in control of who is op'd in their own servers. I'll probably open an issue on Resonant Rise to change their default EiraIRC configuration since we can't see eye to eye on this, and we can agree to disagree on this matter?

At least you got something accidentally fixed :)
