### ISSUE TITLE
Dircord Integration

### ISSUE THREAD

**Issue by BarbasTheDog** [blay09/EiraIRC#350]
Discord is a free voice chat + text platform focused on gaming. The text channels are rather similar in function to IRC.

I tried it for the first time today and was sad to s find out there isn't a Forge MC-Discord bridge yet. Discord is becoming increasingly popular, so I can see this becoming a widely requested feature in the future.

**Comment by BlayTheNinth** [comment]
If you're looking for a server bridge, check out http://minecraft.curseforge.com/projects/discordchat

**Comment by BarbasTheDog** [comment]
Ah, thanks for pointing that out. I only saw shadowfacts' post on reddit saying she'd have a jab at it after I wrote this issue. Thanks ^ ^
