### ISSUE TITLE
Unstable Connection When Not In World

### ISSUE THREAD

**Issue by willies952002** [blay09/EiraIRC#351]
When a player is not in a world (sitting on the main menu), the bot constantly disconnects and reconnects every 10-30 seconds, spamming the IRC chat with connect/disconnect messages.

Version: 1.7.10-2.9.396
Forge: 10.13.4.1614 (1.7.10)

Here's what is happening in the IRC chat: https://hasteb.in/asurafegiy.txt

If you need more information, please let me know.

**Comment by BlayTheNinth** [comment]
Is there anything in the Minecraft client log related to the reconnects? I've tried to reproduce it, but it stays connected for me.

**Comment by willies952002** [comment]
I found this in the log:

> [07:28:13] [IRC (irc.spi.gt)/INFO]: [CHAT] EiraIRC encountered an unexpected error! The connection to irc.spi.gt was closed.

I have a sneaking suspicion that the disconnects are due to the mod not responding to the server when it receives a PING since when it reconnects the server says:

> [07:28:29] [IRC (irc.spi.gt)/INFO]: [CHAT] [(elmer.spi.gt)] **\* If you are having problems connecting due to ping timeouts, please type /quote PONG n]iM`cGqmJ or /raw PONG n]iM`cGqmJ no

**Comment by BlayTheNinth** [comment]
It's an intentional disconnect, ping timeouts would result in a different quit message.
It seems something is crashing the connection - the important part of the log (the stacktrace) should be right below in the log of what you've posted.

**Comment by willies952002** [comment]
This is all I see in the log repeating over and over.

> [07:27:55] [IRC (irc.spi.gt)/INFO]: [CHAT] EiraIRC encountered an unexpected error! The connection to irc.spi.gt was closed.
> 
> [07:27:55] [IRC (irc.spi.gt)/INFO]: [CHAT] See the log file for more details.
> 
> [07:28:11] [IRC (irc.spi.gt)/INFO]: [CHAT] [(elmer.spi.gt)] **\* If you are having problems connecting due to ping timeouts, please type /quote PONG [STRING] or /raw PONG [STRING] now.
> 
> [07:28:13] [IRC (irc.spi.gt)/INFO]: [CHAT] [(NickServ)] Welcome to SpigotMC, willies952002-mc! Here on SpigotMC, we provide services to enable the registration of nicknames and channels! For details, type §l/msg NickServ help§l and §l/msg ChanServ help§l.
> 
> [07:28:13] [IRC (irc.spi.gt)/INFO]: [CHAT] [#spigot] Spigot, performance savvy Vanilla replacement! | 1.8 is here! http://bit.ly/123qiHf | http://www.spigotmc.org/ | BungeeCord support in #md_5 | TeamSpeak @ talk.spigotmc.org | Rules: http://j.md-5.net/1ikUQuU | #spigot-chat for off topic

Image of the log (unmodified): http://i.imgur.com/aAQrp2D.png

**Comment by BlayTheNinth** [comment]
Okay. Can you try running this build? I made it crash properly instead of just complaining in the log, so we should be able to see what's causing it then.

http://jenkins.blay09.net/job/EiraIRC%201.7.10/399/

Thanks, you may just turn out to be the saviour of esper.net.

**Comment by willies952002** [comment]
Loading up the client now, just waiting for all 120 mods to load up =P

**Comment by willies952002** [comment]
Okay, after some time I myself got the mod to crash. here's the stacktrace:

> java.lang.NullPointerException: Exception in IRC Connection irc.spi.gt
> . . . at net.blay09.mods.eirairc.client.ClientProxy.checkClientBridge(ClientProxy.java:187)
> . . . at net.blay09.mods.eirairc.handler.IRCEventHandler.fireChannelChatEvent(IRCEventHandler.java:261)
> . . . at net.blay09.mods.eirairc.irc.IRCConnectionImpl.handleMessage(IRCConnectionImpl.java:476)
> . . . at net.blay09.mods.eirairc.irc.IRCConnectionImpl.run(IRCConnectionImpl.java:236)
> . . . at java.lang.Thread.run(Thread.java:745)

**Comment by BlayTheNinth** [comment]
Awesome. This has been an issue for so long and we could never figure out why the continous reconnects happen. I've learnt my lesson: making things only error and not crash when it really is a crash is a bad idea because no one will ever report it. Fixed builds are on Jenkins or will be up on CurseForge in a bit.

**Comment by willies952002** [comment]
I'll be sure to update, and hopefully the one hour ban I earned from it was worth it xD

Long story short... I was on the Spigot IRC server and was in the main channel when all of errors occurred. One of the half-ops banned me for an hour and messaged my main account letting me know what had happened. At least he understood that it wasn't me doing it on purpose.

**Comment by BlayTheNinth** [comment]
Haha, sorry about the temp-ban, but yes, it was absolutely worth it. :)

**Comment by willies952002** [comment]
It's fine, and I do agree with you, it was well worth it xD
