### ISSUE TITLE
Timeouts and kicks are ignored by EiraIRC

### ISSUE THREAD

**Issue by GinjaNinja32** [blay09/EiraIRC#352]
If you are connected to a server and time out/get DCed, EiraIRC will not notice (until the next message is sent? Not sure on this), to the point of rejecting a `/sirc connect <server>` because it's "already connected to <server>"

If you are in a channel and get kicked, EiraIRC will also not notice, and will also reject a `/sirc join <channel>`, saying "You have joined <channel> in <server> already."

**Comment by MightyStick** [comment]
Hey
