### ISSUE TITLE
Links are not always clickable in chat

### ISSUE THREAD

**Issue by blay09** [blay09/EiraIRC#82]

**Comment by jac2084** [comment]
just adding a +1 to this bug, i know you are working hard but is there any luck finding a fix? 
also love the new gui and features on alpha 8.45

**Comment by blay09** [comment]
I'll have a look at this bug specifically tomorrow.

**Comment by blay09** [comment]
I had a look and it's pretty obvious why it's not working, but pretty hard for me to fix, as that stuff is located in Vanilla code with no real way for me to hook in. It is clearly not related to EiraIRC, it's just Mojang apparently completely forgetting about user-typed chat links. 

I have a fix in mind (though it's really more of an ugly workaround) and I'll add it a bit later once I've recovered from my Mojang-Code shock.
